-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 11:12:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projectx
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projectx` DEFAULT CHARACTER SET utf8 ;
USE `projectx` ;

-- -----------------------------------------------------
-- Table `projectx`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`user` ;

CREATE TABLE IF NOT EXISTS `projectx`.`user` (
  `id` INT NOT NULL,
  `full_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `creation_date` VARCHAR(20) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`posts` ;

CREATE TABLE IF NOT EXISTS `projectx`.`posts` (
  `id` INT NOT NULL,
  `creation_data` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  INDEX `posts_fk_idx` (`id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `posts_fk`
    FOREIGN KEY (`id`)
    REFERENCES `projectx`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`followers` ;

CREATE TABLE IF NOT EXISTS `projectx`.`followers` (
  `follower_id` INT NOT NULL,
  `following_id` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`comments` ;

CREATE TABLE IF NOT EXISTS `projectx`.`comments` (
  `id` INT NOT NULL,
  `comment` VARCHAR(500) NOT NULL,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  INDEX `commnets_fk_idx` (`id` ASC) VISIBLE,
  CONSTRAINT `commnets_fk`
    FOREIGN KEY (`id`)
    REFERENCES `projectx`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_fk`
    FOREIGN KEY ()
    REFERENCES `projectx`.`posts` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`media` ;

CREATE TABLE IF NOT EXISTS `projectx`.`media` (
  `id` INT NOT NULL,
  `media_type` VARCHAR(100) NOT NULL,
  `media_url` VARCHAR(100) NOT NULL,
  `post_id` INT NOT NULL,
  INDEX `media_fk_idx` (`id` ASC, `post_id` ASC) VISIBLE,
  CONSTRAINT `media_fk`
    FOREIGN KEY (`id` , `post_id`)
    REFERENCES `projectx`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projectx`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projectx`.`favorites` ;

CREATE TABLE IF NOT EXISTS `projectx`.`favorites` (
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
